import "@/src/app/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { headers } from "next/headers";
import { type ReactNode } from "react";
import { Providers } from "@/src/lib/providers";
import { cookieToInitialState } from "wagmi";
import { getConfig } from "@/src/lib/wagmi";

const inter = Inter({ subsets: ["latin"] });

// SEO标签
// <title>Create Wagmi</title>
// <meta name="description" content="Generated by create-wagmi" />
export const metadata: Metadata = {
  title: "Create Wagmi",
  description: "Generated by create-wagmi",
};

export default async function RootLayout(props: { children: ReactNode }) {
  // 服务器端获取cookie
  const cookie = (await headers()).get("cookie");
  const initialState = cookieToInitialState(getConfig(), cookie);

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers initialState={initialState}>{props.children}</Providers>
      </body>
    </html>
  );
}
